export const BASE_URL = 'https://codequiz-backend.onrender.com';

export const ALL_COUNTRY = [
  "India",
  "United States",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "United Kingdom",
  "Japan",
  "China",
  "Russia",
  "South Africa",
  "Brazil",
  "Mexico",
  "Spain",
  "Italy",
  "Turkey",
  "Egypt",
  "Saudi Arabia",
  "Morocco",
  "Algeria",
  "Tunisia",
  "Nigeria",
  "Ghana",
  "Senegal",
  "Cameroon",
  "Gabon",
  "Congo",
  "Angola",
  "Chad",
  "Sudan",
  "Libya",
  "Yemen",
  "Syria",
  "Iraq",
  "Jordan",
  "Lebanon",
  "Kuwait",
  "Oman",
  "Qatar",
  "Bahrain",
  "United Arab Emirates",
  "Iran",
  "Afghanistan",
  "Pakistan",
  "Nepal",
  "Bangladesh",
  "Bhutan",
  "Sri Lanka",
  "Maldives",
  "Azerbaijan",
  "Georgia",
  "Armenia",
  "Tajikistan",
  "Uzbekistan",
  "Kyrgyzstan",
  "Turkmenistan",
  "Kazakhstan",
  "Albania", 
  "Andorra", 
  "Argentina", 
  "Austria", 
  "Belarus", 
  "Belgium",
  "Bolivia", 
  "Bosnia and Herzegovina", 
  "Botswana", "Bulgaria", 
  "Burkina Faso",
  "Burundi", 
  "Cambodia", 
  "Chile", 
  "Colombia", 
  "Costa Rica", 
  "Croatia",
  "Cuba", 
  "Cyprus", 
  "Czech Republic", 
  "Democratic Republic of the Congo",
  "Denmark", 
  "Dominican Republic", 
  "Ecuador", 
  "Estonia", 
  "Ethiopia",
  "Finland", 
  "Greece", 
  "Guatemala", 
  "Guinea", 
  "Guinea-Bissau", 
  "Guyana",
  "Haiti", 
  "Honduras", 
  "Hungary", "Iceland", "Indonesia", "Ireland",
  "Israel", 
  "Ivory Coast", 
  "Kenya", "Laos", "Latvia", "Lithuania",
  "Luxembourg", 
  "Madagascar", 
  "Malawi", 
  "Malaysia", 
  "Mali", 
  "Malta",
  "Mauritania", "Mauritius", "Moldova", "Monaco", "Mongolia", "Montenegro",
  "Mozambique", "Myanmar", "Namibia", "Netherlands", "New Zealand",
  "Nicaragua", "Niger", "North Korea", "North Macedonia", "Norway",
  "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
  "Poland", "Portugal", "Romania", "Rwanda", "Singapore", "Slovakia",
  "Slovenia", "Somalia", "South Korea", "South Sudan", "Sweden",
  "Switzerland", "Taiwan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Uganda",
  "Ukraine", "Uruguay", "Venezuela", "Vietnam", "Zambia", "Zimbabwe"
]